#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Mar 01 16:38:54 GMT 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ad1d7fb9c8c449059401d30cef3286da --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RAM_8x8_tb_behav xil_defaultlib.RAM_8x8_tb -log elaborate.log"
xelab -wto ad1d7fb9c8c449059401d30cef3286da --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RAM_8x8_tb_behav xil_defaultlib.RAM_8x8_tb -log elaborate.log

