#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Feb 29 19:23:21 GMT 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 74e1bea764494c9c8600b42d9579c59c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mux_4_to_1_tb_behav xil_defaultlib.mux_4_to_1_tb -log elaborate.log"
xelab -wto 74e1bea764494c9c8600b42d9579c59c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mux_4_to_1_tb_behav xil_defaultlib.mux_4_to_1_tb -log elaborate.log

