#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Mar 01 14:23:51 GMT 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 095c8d3c439046dbb122b624bb01b658 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Rom_16x8_tb_behav xil_defaultlib.Rom_16x8_tb -log elaborate.log"
xelab -wto 095c8d3c439046dbb122b624bb01b658 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Rom_16x8_tb_behav xil_defaultlib.Rom_16x8_tb -log elaborate.log

