#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Mar 01 09:41:26 GMT 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ef2bb7cb5fae41b29d9bc8329a366590 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clk_div_tb_func_synth xil_defaultlib.clk_div_tb -log elaborate.log"
xelab -wto ef2bb7cb5fae41b29d9bc8329a366590 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clk_div_tb_func_synth xil_defaultlib.clk_div_tb -log elaborate.log

